name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello world!"
      - name: test kustomize
        run: kustomize version
      - name: Print Good Bye
        run: echo "Done - Bye!"
